### ISSUE TITLE
Errores Js presentes al realizar una búsqueda sin completar todos los datos

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-ferrer#13]
![imagen](https://github.com/UCC-LabCompu2/proyecto2024-ferrer/assets/8345007/022565d9-a6ac-43af-a763-e60b8cd1f29b)

**Comment by edme88** [comment]
También se producen múltiples errores en el Js al registrarse:
![imagen](https://github.com/UCC-LabCompu2/proyecto2024-ferrer/assets/8345007/a9531474-5b83-42cb-a15a-37da5ce11ac9)

**Comment by danteferrer** [comment]
no me parece el error y tampoco me deja pasar sin completar todo

![Captura de pantalla 2024-07-01 122439](https://github.com/UCC-LabCompu2/proyecto2024-ferrer/assets/135678008/a76a9df6-cf6e-4152-a70d-edcc34d12d2b)
