### ISSUE TITLE
Errores presentes al realizar un inspect code

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-ferrer#9]
![imagen](https://github.com/UCC-LabCompu2/proyecto2024-ferrer/assets/8345007/e24b123b-055e-4b1b-b073-0a4ae48bfac1)

**Comment by danteferrer** [comment]
![Captura de pantalla 2024-06-15 121247](https://github.com/UCC-LabCompu2/proyecto2024-ferrer/assets/135678008/2f48f143-1dbe-4fb3-8ec6-a03c1a0a6f50)
puedo estar equibocado pero no me aprece ningun error
